# Configuration for Label Commenter - ./.github/label-commenter-config.yml
name: Label Commenter

on:
  issues:
    types: [ labeled ]
  pull_request:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  comment:
    if: github.repository_owner == 'seleniumhq'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to get config file
        uses: actions/checkout@v4
      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        with:
          # The individual PAT is needed so commenter can auto-executes on PRs from Forks
          # It expires 4/1/2026
          github_token: ${{ secrets.LABEL_COMMENTER_PAT }}
