# Configuration for Label Generation - ./.github/pr-labeler-config.yml
name: Label pull requests based on file paths

on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Auto label Pull Requests
        uses: actions/labeler@v5
        with:
          # The individual PAT is needed so labeler auto-executes this workflow
          # It expires 4/1/2026
          repo-token: ${{ secrets.PR_LABELER_PAT }}
          configuration-path: .github/pr-labeler-config.yml
