name: Update Documentation

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (e.g., 4.21.0)
        required: true
        type: string
      language:
        description: language documentation
        required: true
        type: choice
        default: "all"
        options:
          - java
          - rb
          - py
          - dotnet
          - node
          - all

  workflow_call:
    inputs:
      version:
        required: true
        type: string
      sha:
        required: true
        type: string
      language:
        required: false
        type: string
        default: "all"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  determine-languages:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.set-languages.outputs.languages }}
    steps:
      - id: set-languages
        run: |
          if [ "${{ inputs.language }}" == "all" ]; then
            echo '"languages=java rb py dotnet node" >> $GITHUB_OUTPUT
          else
            echo "languages=${{ inputs.language }}" >> $GITHUB_OUTPUT
          fi

  build-docs:
    needs: determine-languages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || inputs.sha }}
      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages
      - name: Setup git
        run: |
          git config --local user.email "selenium-ci@users.noreply.github.com"
          git config --local user.name "Selenium CI Bot"
      - name: Setup curl for Ubuntu
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      - name: Setup Java
        if: contains(needs.determine-languages.outputs.languages, 'java')
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Python 3.9
        if: contains(needs.determine-languages.outputs.languages, 'py')
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        if: contains(needs.determine-languages.outputs.languages, 'py')
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Install npm dependencies
        if: contains(needs.determine-languages.outputs.languages, 'node')
        run: |
          npm install
          npm install --prefix javascript/selenium-webdriver
      - name: Generate Documentation for selected langauges
        run: |
          read -r -a LANGS <<< "${{ needs.determine-languages.outputs.languages }}"
          for lang in "${LANGS[@]}"; do
            echo "Generating docs for $lang"
            ./go $lang:docs
          done
      - name: Documentation Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SELENIUM_CI_TOKEN }}
          author: Selenium CI Bot <selenium-ci@users.noreply.github.com>
          delete-branch: true
          branch: api-docs-${{ inputs.version }}
          base: gh-pages
          add-paths: docs/api/**
          title: Update documentation for Selenium ${{ inputs.version }}
          body: |
            This PR updates the API documentation for version **${{ inputs.version }}**.
            Languages updated: ${{ needs.determine-languages.outputs.languages }}

            - Auto-generated by [workflow run #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: B-docs
          draft: false
      - name: Enable Pull Request Auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.SELENIUM_CI_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
