name: Update Version After Docs Merge

on:
  pull_request:
    types: [closed]
    branches:
      - gh-pages
    paths:
      - 'docs/api/**'

jobs:
  update-version:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'Update documentation for Selenium')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trunk branch
        uses: actions/checkout@v4
        with:
          ref: trunk
          token: ${{ secrets.SELENIUM_CI_TOKEN }}

      - name: Setup git
        run: |
          git config --local user.email "selenium-ci@users.noreply.github.com"
          git config --local user.name "Selenium CI Bot"

      - name: Update versions to nightly
        run: ./go all:version nightly

      - name: Bump Nightly Versions Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.SELENIUM_CI_TOKEN }}
          author: Selenium CI Bot <selenium-ci@users.noreply.github.com>
          delete-branch: true
          branch: bump-nightly-version
          title: Update to nightly versions
          body: |
            This PR bumps the bindings to nightly versions after merging
            the PR updating the API documentation.

            - Auto-generated by [workflow run #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          labels: B-docs
          draft: false
      - name: Enable Pull Request Auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.SELENIUM_CI_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
